import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import axios from 'axios';
import MUIDataTable from 'mui-datatables';
import { createMuiTheme, MuiThemeProvider } from '@material-ui/core';
import {FreeEDRIconButton} from '../components/FreeEDRIconButton.js';

export class AppDashboardMaintenance extends Component {
	constructor(props){
		super(props);
		this.state = {
			reports: []
		};
		this.handleFileOpen = this.handleFileOpen.bind(this);
	};

	componentDidMount() {
		axios.get(`http://localhost:56705/Reporting.svc/GetReports`)
		  .then(res => {
			const data = res.data.GetReportsResult;
			const reportList = [];
			for(var i = 0; i < data.length; i++){
				const newData = [];
				var text = data[i];
				var report = text.substr(28, text.length);
				var name = "Event Report " + report.substr(7, 1);
				var date = report.substr(9, text.length - 4);
				date = date.substr(0, date.length - 4);
				var dateParams = date.split('_');
				var dateFormat = new Date(dateParams[0], dateParams[2], dateParams[1], dateParams[3], dateParams[4], dateParams[5])
				newData[i] = [name, dateFormat.toDateString(), text, 'API', 'http://127.0.0.1:8887/' + report];
				reportList[i] = newData[i];
			}
			this.setState({ reports: reportList });
		  })
	}

	handleFileOpen(value){
		console.log(value);
		window.open(value);
	}


	render(){
		const { reports } = this.state;
		console.log(reports);
		const options = {
			filterType: 'dropdown',
			selectableRows: false,
			downloadOptions: {
				filename: 'RecentReports.csv', separator: ','
			},
			rowsPerPage: 7,
		    rowsPerPageOptions: [5,7,9],
		};
		const chipTheme = createMuiTheme({
			palette: {
			  primary: { main: '#11cb5f' },
			  secondary: { main: '#ff0000' },
			  error: { main: '#8c8c8c' }
			},
			typography: { useNextVariants: true },
		  });
		  // sample data
		const columns = [
			{
				name: "Report",
				options:{
					filter: true,
					display: 'true'
				}
			},
			{
				name: "DateTime",
				options:{
					filter: true,
					display: 'true'
				}
			},
			{
				name: "File Location",
				options:{
					filter: false,
					display: 'false'
				}
			},
			{
				name: "Generated By",
				options: {
					filter: true,
					display: 'true'
				}
			},
			{
				name: "Download",
				options: {
					filter: false,
					display: 'true',
					sort: false,
					customBodyRender: (value, tableMeta, updateValue) => {
						return (
							<FreeEDRIconButton color="Primary" airaLabel="Download Report" icon="create" onClick={() => {this.handleFileOpen(value)}}/>
						)
					}
				}
			}];
		return (
			<div id="descriptionContent">
				<h3> FreeEDR Senior Design Home Page </h3>
				<h4> Below is the list of reports that were recently generated by the system users.</h4>
				<h4> In order to download the reports, please double click on the intended icon in the row of the report.</h4>
				<MUIDataTable title={"Recent Reports"} data={reports} columns={columns} options={options}/>
			</div>
		)
	}
}