import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import axios from 'axios';
import MUIDataTable from 'mui-datatables';


export class AppDashboardMaintenance extends Component {
	constructor(props){
		super(props);
		this.state = {
		
		};
	};

	render(){
		const { site } = this.props;
		return (
			<div id="descriptionContent">
				<h3> FreeEDR Senior Design Home Page </h3>
				<h4> Below is the list of reports that were recently generated by the system users.</h4>
				<h4> In order to view the reports, please double click on the intended icon in the row of the report.</h4>
			</div>
		)
	}
}