import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import axios from 'axios';
import MUIDataTable from 'mui-datatables';
import {Select, Paper, InputLabel, MenuItem, Grid, Button, AppBar, Tab, Tabs, Radio, RadioGroup, FormHelperText, FormControlLabel, FormControl, FormLabel, TextField} from '@material-ui/core';
import { createMuiTheme, MuiThemeProvider } from '@material-ui/core';
import {FreeEDRIconButton} from '../components/FreeEDRIconButton.js';
import InsertDriveFileIcon from '@material-ui/icons/InsertDriveFile';
export class Audit extends Component {
    constructor(props){
		super(props);
		this.state = {
			value: 0
		};
		this.handleChange = this.handleChange.bind(this);
	};

	handleChange(event, value){
	    this.setState({
	    	 value: value 
		});
	}

	render(){
		const { site } = this.props;
		const { value } = this.state;

		const data = [
			["Daily Audit Log", "11-3-2019 10:05:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_11_3_19_10_12.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_11_3_19_10_05.log"],
			["Daily Audit Log", "10-29-2019 10:05:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_10_29_19_10_12.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_10_29_19_10_12.log"],
			["Daily Audit Log", "10-28-2019 10:05:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_10_28_19_10_12.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_10_28_19_10_12.log"],
		];

		const systemData = [
			["SOC1 Audit", "11-3-2019 10:05:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\soc1.pdf", "SystemAuditor", "C:\\inetpub\\LogFiles\\wscvsm1\\soc1.pdf"],
			["Internal Controls Audit", "10-29-2019 10:05:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\internal.pdf", "SystemAuditor", "C:\\inetpub\\LogFiles\\wscvsm1\\internal.pdf"],
			["Workstation Audit", "10-28-2019 10:05:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\workstation.pdf", "SystemAuditor", "C:\\inetpub\\LogFiles\\wscvsm1\\workstation.pdf"],
			["Daily Audit Log", "11-3-2019 10:05:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_11_3_19_10_12.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_11_3_19_10_05.log"],
			["Daily Audit Log", "10-29-2019 10:05:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_10_29_19_10_12.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_10_29_19_10_12.log"],
			["Daily Audit Log", "10-28-2019 10:05:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_10_28_19_10_12.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyAudit_10_28_19_10_12.log"],
		];

		const options = {
			filterType: 'dropdown',
			selectableRows: false,
			downloadOptions: {
				filename: 'RecentAudits.csv', separator: ','
			},
			rowsPerPage: 3,
		    rowsPerPageOptions: [3,5,8],
		};

		const theme = {
			spacing: 8,
		};
		const columns = [
			{
				name: "Report",
				options:{
					filter: true,
					display: 'true'
				}
			},
			{
				name: "DateTime",
				options:{
					filter: true,
					display: 'true'
				}
			},
			{
				name: "File Location",
				options:{
					filter: false,
					display: 'false'
				}
			},
			{
				name: "Generated By",
				options: {
					filter: true,
					display: 'true'
				}
			},
			{
				name: "Download",
				options: {
					filter: false,
					display: 'true',
					sort: false,
					customBodyRender: (value, tableMeta, updateValue) => {
						return (
							<FreeEDRIconButton color="Primary" airaLabel="Download Report" icon="create"/>
						)
					}
				}
			}];

		return (
			<div id="descriptionContent">
				<h3> FreeEDR Senior Design Audit Page </h3>
				<AppBar position="static">
				<Tabs value={value} onChange={this.handleChange} aria-label="simple tabs example">
					<Tab label="Internal Auditing System"/>
					<Tab label="View Previous Audits"/>
				</Tabs>
				</AppBar>
				{value === 0 && <div id="content">
				<br></br>
				<MUIDataTable title={"Recent Audits"} data={data} columns={columns} options={options}/>
				<br></br>
				<h3>Generate Audits</h3>
				<Grid container spacing={24}>
					<Grid item xs={6} sm={6}>
					<Paper>
						<Button variant="contained" color="default">
							<InsertDriveFileIcon/>	SOC1 Report
						</Button>
						<br></br> <br></br>
						<Button variant="contained"	color="default">
						<InsertDriveFileIcon/>	Internal Audit Report
						</Button>
						<br></br> <br></br>
						<Button variant="contained"	color="default">
						<InsertDriveFileIcon/>	Workstation Report
						</Button>
						<br></br> <br></br>
						<Button variant="contained"	color="default">
						<InsertDriveFileIcon/>	Full System Audit
						</Button>
					</Paper>
					</Grid>
					</Grid>
				</div>}
				{value === 1 && <div id="content">
				<h4> Below is the list of audits that were recently generated by system auditors.</h4>
				<h4> In order to download the reports, please double click on the intended icon in the row of the report.</h4>
				<MUIDataTable title={"Recent Audits"} data={systemData} columns={columns} options={options}/></div>}
			</div>
		)
	}

}