import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import axios from 'axios';
import MUIDataTable from 'mui-datatables';
import {Select, Paper, InputLabel, MenuItem, Grid, Button, AppBar, Tab, Tabs, Radio, RadioGroup, FormHelperText, FormControlLabel, FormControl, FormLabel, TextField} from '@material-ui/core';
import { createMuiTheme, MuiThemeProvider } from '@material-ui/core';
import {FreeEDRIconButton} from '../components/FreeEDRIconButton.js';
import InsertDriveFileIcon from '@material-ui/icons/InsertDriveFile';
import {BgReportDialog} from '../src/AppDashboard.Helper-1.0.0.0.js';
export class Reports extends Component {
    constructor(props){
		super(props);
		this.state = {
			value: 0,
			reports: []
		};
		this.handleFileOpen = this.handleFileOpen.bind(this);
		this.handleChange = this.handleChange.bind(this);
		this.launchReportDialog = this.launchReportDialog.bind(this);
	};

	handleChange(event, value){
	    this.setState({
	    	 value: value 
		});
	}

	componentDidMount() {
		axios.get(`http://localhost:56705/Reporting.svc/GetReports`)
		  .then(res => {
			const data = res.data.GetReportsResult;
			const reportList = [];
			for(var i = 0; i < data.length; i++){
				const newData = [];
				var text = data[i];
				var report = text.substr(28, text.length);
				var name = "Event Report " + report.substr(7, 1);
				var date = report.substr(9, text.length - 4);
				date = date.substr(0, date.length - 4);
				var dateParams = date.split('_');
				var dateFormat = new Date(dateParams[0], dateParams[2], dateParams[1], dateParams[3], dateParams[4], dateParams[5])
				newData[i] = [name, dateFormat.toDateString(), text, 'API', 'http://127.0.0.1:8887/' + report];
				reportList[i] = newData[i];
			}
			this.setState({ reports: reportList });
		  })
	}

	handleFileOpen(value){
		console.log(value);
		window.open(value);
	};

	launchReportDialog(){
		BgReportDialog.showModal();
	}


	render(){
		const { site } = this.props;
		const { value, reports } = this.state;
		const options = {
			filterType: 'dropdown',
			selectableRows: false,
			downloadOptions: {
				filename: 'RecentReports.csv', separator: ','
			},
			rowsPerPage: 5,
		    rowsPerPageOptions: [3,5,8],
		};
		const chipTheme = createMuiTheme({
			palette: {
			  primary: { main: '#11cb5f' },
			  secondary: { main: '#ff0000' },
			  error: { main: '#8c8c8c' }
			},
			typography: { useNextVariants: true },
		  });

		const loggingData = [
			["Daily IIS Log", "11-3-2019 10:10:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyIIS_11_3_19_10_10.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyIIS_11_3_19_10_10.log"],
			["User Application Log", "11-1-2019 10:12:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\userApp_11_1_19_10_12.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\userApp_11_1_19_10_12.log"],
			["Daily IIS Log", "10-29-2019 10:10:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyIIS_10_29_19_10_10.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyIIS_10_29_19_10_10.log"],
			["User Application Log", "10-29-2019 10:12:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\userApp_10_29_19_10_12.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\userApp_10_29_19_10_12.log"],
			["Daily IIS Log", "10-28-2019 10:10:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyIIS_10_28_19_10_10.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\dailyIIS_10_28_19_10_10.log"],
			["User Application Log", "10-28-2019 10:12:00Z", "C:\\inetpub\\LogFiles\\wscvsm1\\userApp_10_28_19_10_12.log", "IncidentTeam", "C:\\inetpub\\LogFiles\\wscvsm1\\userApp_10_28_19_10_12.log"],
		];

		const deploymentData = [
		];

		const theme = {
			spacing: 8,
		};
		const columns = [
			{
				name: "Report",
				options:{
					filter: true,
					display: 'true'
				}
			},
			{
				name: "DateTime",
				options:{
					filter: true,
					display: 'true'
				}
			},
			{
				name: "File Location",
				options:{
					filter: false,
					display: 'false'
				}
			},
			{
				name: "Generated By",
				options: {
					filter: true,
					display: 'true'
				}
			},
			{
				name: "Download",
				options: {
					filter: false,
					display: 'true',
					sort: false,
					customBodyRender: (value, tableMeta, updateValue) => {
						return (
							<FreeEDRIconButton color="Primary" airaLabel="Download Report" icon="create" onClick={() => {this.handleFileOpen(value)}}/>
						)
					}
				}
			}];
		return (
			<div id="descriptionContent">
				<h3> FreeEDR Senior Design Reports Page </h3>
				<AppBar position="static">
				<Tabs value={value} onChange={this.handleChange} aria-label="simple tabs example">
					<Tab label="Daily Event Report"/>
					<Tab label="Rule Deployment Report"/>
					<Tab label="Logging Reports"/>
					<Tab label="View Previous Reports"/>
				</Tabs>
				</AppBar>
				{value === 0 && <div id="content">
				<br></br>
				<MUIDataTable title={"Recent Event Reports"} data={reports} columns={columns} options={options}/>
				<br></br>
				<h3>Generate Reports</h3>
				<Button variant="contained" color="default" onClick={() => {this.launchReportDialog()}}>
					<InsertDriveFileIcon/>	Open Event Dialog
				</Button>				
				</div>}
				{value === 1 && <div id="content">
				<br></br>
				<MUIDataTable title={"Recent Deployment Reports"} data={deploymentData} columns={columns} options={options}/>
				<br></br>
				<h3>Generate Reports</h3>
				<Button variant="contained" color="default" onClick={() => {this.launchReportDialog()}}>
					<InsertDriveFileIcon/>	Open Deployment Dialog
				</Button>			
				</div>}
				{value === 2 && <div id="content">
				<br></br>
				<MUIDataTable title={"Recent Logging Reports"} data={loggingData} columns={columns} options={options}/>
				<br></br>
				<h3>Generate Reports</h3>
				<Button variant="contained" color="default">
					<InsertDriveFileIcon/>	Open Logging Dialog
				</Button>
				</div>}
				{value === 3 && <div id="content">
				<h4> Below is the list of reports that were recently generated by the system users.</h4>
				<h4> In order to download the reports, please double click on the intended icon in the row of the report.</h4>
				<MUIDataTable title={"Recent Reports"} data={reports} columns={columns} options={options}/></div>}
			</div>
		)
	}

}